
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.HashSet;
import java.util.Set;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    //set Remember username & password
//    public Preferences pref = Preferences.userRoot().node("Rememberme");
    
    public LoginForm() {
        initComponents();
        
        //set center form
        this.setLocationRelativeTo(null);
        
        //create border for global panel
        Border glo_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        
        //create border for minimize & close
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        label_mini.setBorder(label_border);
        label_close.setBorder(label_border);
        
        //create boder for panel name login
        Border panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(134,226,213));
        jPanel_name.setBorder(panel_border);
        
//        String u = null;
//        u = pref.get("Username", u);
//        username.setText(u);
//        
//        String p = null;
//        p = pref.get("Password", p);
//        password.setText(p);
    }

    
 
    //Set color linear for login form
    class jPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
          
            Color color1 = new Color(41, 241, 195);
            Color color2 = new Color(27, 163, 156);
            GradientPaint gp = new GradientPaint(0, 0, color1, 90, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        label_close = new javax.swing.JLabel();
        label_mini = new javax.swing.JLabel();
        jPanel_name = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        label_pass = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        user_icon = new javax.swing.JLabel();
        pass_icon = new javax.swing.JLabel();
        Reset_button = new javax.swing.JButton();
        ShowPass = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));

        label_close.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_close.setText(" X");
        label_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_closeMouseExited(evt);
            }
        });

        label_mini.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        label_mini.setText("  -");
        label_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_miniMouseExited(evt);
            }
        });

        jPanel_name.setBackground(new java.awt.Color(134, 226, 213));
        jPanel_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 126, 126));
        jLabel1.setText("FLIGHT MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Coiny", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 126, 126));
        jLabel2.setText("    LOGIN");

        javax.swing.GroupLayout jPanel_nameLayout = new javax.swing.GroupLayout(jPanel_name);
        jPanel_name.setLayout(jPanel_nameLayout);
        jPanel_nameLayout.setHorizontalGroup(
            jPanel_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nameLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel_nameLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_nameLayout.setVerticalGroup(
            jPanel_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        label_user.setBackground(new java.awt.Color(0, 153, 159));
        label_user.setFont(new java.awt.Font("Baloo Bhai", 0, 18)); // NOI18N
        label_user.setForeground(new java.awt.Color(204, 255, 255));
        label_user.setText("Username:");

        label_pass.setBackground(new java.awt.Color(0, 153, 159));
        label_pass.setFont(new java.awt.Font("Baloo Bhai", 0, 18)); // NOI18N
        label_pass.setForeground(new java.awt.Color(204, 255, 255));
        label_pass.setText("Password:");

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText("username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("password");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(0, 102, 102));
        jButton_login.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(204, 255, 255));
        jButton_login.setText("Log In");
        jButton_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_loginMouseExited(evt);
            }
        });
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-icon (1).png"))); // NOI18N
        user_icon.setPreferredSize(new java.awt.Dimension(32, 32));
        user_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_iconMouseExited(evt);
            }
        });

        pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User-Interface-Password-icon (1).png"))); // NOI18N
        pass_icon.setPreferredSize(new java.awt.Dimension(32, 32));

        Reset_button.setBackground(new java.awt.Color(0, 102, 102));
        Reset_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Reload-icon.png"))); // NOI18N
        Reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Reset_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Reset_buttonMouseExited(evt);
            }
        });
        Reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_buttonActionPerformed(evt);
            }
        });

        ShowPass.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        ShowPass.setForeground(new java.awt.Color(204, 255, 255));
        ShowPass.setText("Show password");
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(jPanel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(label_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_user)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_pass)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(user_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pass_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ShowPass)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton_login))
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(178, 178, 178))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_close)
                    .addComponent(label_mini))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(label_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ShowPass)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        label_mini.setBorder(label_border);
        label_mini.setForeground(Color.red);
    }//GEN-LAST:event_label_miniMouseEntered

    private void label_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        label_mini.setBorder(label_border);
        label_mini.setForeground(Color.black);
    }//GEN-LAST:event_label_miniMouseExited

    private void label_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        label_close.setBorder(label_border);
        label_close.setForeground(Color.red);
    }//GEN-LAST:event_label_closeMouseEntered

    private void label_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        label_close.setBorder(label_border);
        label_close.setForeground(Color.black);
    }//GEN-LAST:event_label_closeMouseExited

    private void label_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label_miniMouseClicked

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_label_closeMouseClicked

    private void jButton_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseEntered
        
        //set jButton_login background
        jButton_login.setBackground(new Color(0,101,183));
        
        
    }//GEN-LAST:event_jButton_loginMouseEntered

    private void jButton_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseExited
        
        //set jButton_login background
        jButton_login.setBackground(new Color(0,84,104));
        
    }//GEN-LAST:event_jButton_loginMouseExited

    private void jButton_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseClicked

    }//GEN-LAST:event_jButton_loginMouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        
        //clear "username" om the textfield
        if(username.getText().trim().toLowerCase().equals("username"))
        {
            username.setText("");
            username.setForeground(Color.black);
        }
        
        //set border for label_user
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        label_user.setBorder(label_border);
        user_icon.setBorder(label_border);
        
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        
        //if the text is "username" or empty
        //set the text is "username"
        if(username.getText().trim().equals("") || 
           username.getText().trim().toLowerCase().equals("username"))
        {
            username.setText("username");
            username.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        label_user.setBorder(null);
        user_icon.setBorder(null);
        
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        
        //clear .... in the password field
        
        //get the password text
        String pas = String.valueOf(password.getPassword());
        
        if(pas.trim().toLowerCase().equals("password"))
        {
            password.setText("");
            password.setForeground(Color.black);
        }
        
        //set border for label_pass
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        label_pass.setBorder(label_border);
        pass_icon.setBorder(label_border);
        
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        
        //if the text is "password" or empty
        //set the text is "password"
        
        //get the password text
        String pas = String.valueOf(password.getPassword());
        
        if(pas.trim().equals("") || pas.trim().toLowerCase().equals("password"))
        {
            password.setText("password");
            password.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        label_pass.setBorder(null);
        pass_icon.setBorder(null);
        
    }//GEN-LAST:event_passwordFocusLost

    private void user_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_iconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user_iconMouseEntered

    private void user_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_iconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user_iconMouseExited

    private void Reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_buttonActionPerformed
        
        //set reset for reset button
        username.setText(null);
        password.setText(null);
        
    }//GEN-LAST:event_Reset_buttonActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        
        //show password
        if(evt.getSource() == ShowPass)
        {
            if(ShowPass.isSelected())
            {
                password.setEchoChar((char) 0);
            }
            else
            {
                password.setEchoChar('*');
            }
        }
        
    }//GEN-LAST:event_ShowPassActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        String user = username.getText();
        String pass = password.getText();
        
        if((pass.contains("123456789")) && (user.contains("admin")))
        {
            username.setText(null);
            password.setText(null);
            systemExit();
            
            dashboard menu = new dashboard();
            menu.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid Login Details!", "Login Error!", JOptionPane.ERROR_MESSAGE);
            username.setText(null);
            password.setText(null);
        }
        
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void Reset_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset_buttonMouseEntered
         //set jButton_login background
        Reset_button.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_Reset_buttonMouseEntered

    private void Reset_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset_buttonMouseExited
        //set jButton_login background
        Reset_button.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_Reset_buttonMouseExited

    // REMEMBER LOGIN
//    public void saveuserpass(String User, String Pass){
//        if(User == null || Pass == null){
//            System.out.println("Please enter the username and password before!!!");
//        }
//        else{
//            String user = User;
//            pref .put("Username", User);
//            String pass = Pass;
//            pref.put("Password", Pass);
//            System.out.println("Account saved!");
//        }
//    }
//    
//    public final void checked(boolean remember){
//        if(remember = true){
//            saveuserpass(username.getText(), password.getText());
//        }
//        else{
//            System.out.println("Null characters");
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset_button;
    private javax.swing.JRadioButton ShowPass;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_name;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_mini;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_user;
    private javax.swing.JLabel pass_icon;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel user_icon;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    private void systemExit() {
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }

}
